[package]
name = "airkorea"
version = "0.1.2"
authors = ["pbzweihander <sd852456@naver.com>"]
description = "Limitless Airkorea API wrapper"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/airkorea/"
repository = "https://github.com/pbzweihander/airkorea-rs"
readme = "README.md"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
kuchiki = "0.7"
reqwest = "0.8"
regex = "1.0"
lazy_static = "1.1"
failure = "0.1"
hjson2json = "0.1"
