[package]
name = "airkorea"
version = "0.1.0"
authors = ["pbzweihander <sd852456@naver.com>"]
description = "Limitless Airkorea API wrapper"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/airkorea/"
repository = "https://github.com/pbzweihander/airkorea-rs"
readme = "README.md"

[dependencies.hjson2json]
path = "src/hjson2json"
version = "^0.1"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
error-chain = "0.11"
kuchiki = "0.6"
reqwest = "0.8"
regex = "0.2"
lazy_static = "1.0"